name: Build My Application

on: push

jobs:
  build:
    name: Build our App
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Print Current Directory
        run: pwd
      - name: List Filed in Directory
        run: ls
      - name: Check Dotnet Cli
        run: dotnet
      - name: Check NPM Cli
        run: npm